displayName=PersonalProgressTimeline
author=Oyama
support=https://github.com/ItMeansBigMountain/PersonalProgressTimeline
description=PersonalProgressTimeline RuneLite plugin.
tags=personalprogresstimeline,runelite,osrs
plugins=com.itmeansbigmountain.personalprogresstimeline.PersonalProgressTimelinePlugin
